### ISSUE TITLE
Need to fix the hashmap and the ramp subsystem is broken

### ISSUE THREAD

**Issue by LordSquishers** [SarahCovey/Phoenix1797_2018#13]
something is wrong with the ramp system, and the robotmap needs to be fixed. I can fix it after we finish the testing.

**Comment by techtide** [comment]
I can help with this. The Ramp subsystem yields a NullPointerException, which may be due to the lack of the Double Solenoids being connected to the ports. The robot map has commented out code in the latest version which I have e-mailed Sarah.
@LordSquishers, have you tried running the program with the Ramp subsystem and all components of the ramp connected?
Also, @SarahCovey should I do a pull request for the latest running code w/ buttons, etc? Maybe we can create a development branch & a working/tested branch.

**Comment by LordSquishers** [comment]
@techtide the null pointer exception is due to the three times we try to initialize the hashmap.
